export const FETCH_ROOMS = "FETCH_ROOMS";
export const FETCH_ROOM_TYPES = "FETCH_ROOM_TYPES";
export const SET_SELECTED_ROOM_TYPE = "SET_SELECTED_ROOM_TYPE";
export const FILTER_ROOMS = "FILTER_ROOMS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";